version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty12345
      MYSQL_DATABASE: laravel

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: qwerty12345
